# Generated by Django 3.2 on 2021-04-26 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_cat_id', models.CharField(max_length=255, unique=True)),
                ('c_name', models.CharField(max_length=255)),
                ('e_name', models.CharField(max_length=255)),
                ('cat_update_time', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_email', models.CharField(max_length=255)),
                ('contact_addr', models.CharField(max_length=255)),
                ('cover_pic', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('update_time', models.CharField(max_length=255)),
                ('sub_cat_id', models.CharField(max_length=255)),
            ],
        ),
    ]
